#!/usr/bin/env bash
set -e

# todo: 
# create repo

function help() {
  echo "gh extension to save thunder client examples to github"
  echo "  * Assumes the existence of a thunder client directory in the default location for a mac:"
  echo "     $HOME/Library/Application Support/Code/User/globalStorage/rangav.vscode-thunder-client/"
  echo "  * and that the directory is a git repository"
  echo "  * and the remote is in the form:"
  echo "      git@github.com:<user>/rangav.vscode-thunder-client.git"
  echo "Usage:"
  echo "  $0 [-p|--push] [-P|--pull]"
  exit 0
}

POSITIONAL_ARGS=()
while [[ $# -gt 0 ]]; do
  case $1 in
  -p | --push)
    OPTION="push"
    shift # past argument
    ;;
  -P | --pull)
    OPTION="pull"
    shift # past argument
    ;;
  -s | --status)
    OPTION="status"
    shift # past argument
    ;;

  -* | --*)
    help
    ;;
  *)
    POSITIONAL_ARGS+=("$1") # save positional arg
    shift # past argument
    ;;
  esac
done


THUNDER_DIR="$HOME/Library/Application Support/Code/User/globalStorage/rangav.vscode-thunder-client/"
if [ -z "$OPTION" ]; then
  help
fi
cd "$THUNDER_DIR"
ls -list
if [[ "$OPTION" == "push" ]]
then
  git add .
  echo "pushing files from $THUNDER_DIR to $(git remote get-url origin)"

  git commit -m "Update thunder client examples"
  git push -u origin master
elif [[ "$OPTION" == "pull" ]]
then
  echo "pulling files from $(git remote get-url origin) to $THUNDER_DIR"
  git pull origin master
elif [[ "$OPTION" == "status" ]]
then
  git status
fi


